name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 19
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: make build
      - run: make benchmark-bun
      - run: make benchmark-node
